name: mmg
channels:
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - numpy=1.19.2
  - pip:
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.1.2.30
